export const LIST_EQUIPMENTS = 'LIST_EQUIPMENTS';
export const ADD_EQUIPMENT = 'ADD_EQUIPMENT';
export const REMOVE_EQUIPMENTS = 'REMOVE_EQUIPMENTS';
export const SEARCH_EQUIPMENTS = 'SEARCH_EQUIPMENTS';
export const LIST_CALCULATE_EQUIPMENTS = 'LIST_CALCULATE_EQUIPMENTS';
