export const LIST_EQUIPMENTS = 'LIST_EQUIPMENTS';
export const ADD_EQUIPMENT = 'ADD_EQUIPMENT';
export const REMOVE_EQUIPMENTS = 'REMOVE_EQUIPMENTS';
export const SEARCH_EQUIPMENTS = 'SEARCH_EQUIPMENTS';
export const RESET_LIST_EQUIPMENTS = 'RESET_LIST_EQUIPMENTS';
export const EDIT_EQUIPMENTS = 'EDIT_EQUIPMENTS';
export const EDIT_USE_OF_MONTH = 'EDIT_USE_OF_MONTH';

